version: '3'
services:
   db:
      image: kartoza/postgis:12.0
      volumes:
         - geo-db-data:/var/lib/postgresql
      ports:
        - "25434:5432"
      env_file:
      - docker-env/db.env
      restart: on-failure
      healthcheck:
        test: "exit 0"

   geoserver:
      image: kartoza/geoserver:2.17.0
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "8600:8080"
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      depends_on:
        - db
      healthcheck:
        test: ["curl", "--fail", "-s", "http://localhost:8080/", "||", "exit 1"]
        interval: 1m30s
        timeout: 10s
        retries: 3


   db-dbbackups:
     image: kartoza/pg-backup:12.0
     volumes:
     - db-backups:/backups
     env_file:
     - docker-env/db-backups.env
     restart: on-failure
     depends_on:
       - db
  
   pgadmin:
     container_name: pgadmin
     image: dpage/pgadmin4
     volumes:
     - pgadmin:/var/lib/pgadmin
     environment:
       - PGADMIN_DEFAULT_EMAIL=info@moorlandtech.com
       - PGADMIN_DEFAULT_PASSWORD=chei#s5aid9Ietha
     ports:
       - "5050:80/tcp"
     restart: always

volumes:
   db-backups:
   geo-db-data:
   pgadmin:
   geoserver-data:

