apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-dbbackups
  name: db-dbbackups
spec:
  containers:
  - env:
    - name: DUMPPREFIX
      valueFrom:
        configMapKeyRef:
          key: DUMPPREFIX
          name: docker-env-db-backups-env
    - name: POSTGRES_DBNAME
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_DBNAME
          name: docker-env-db-backups-env
    - name: POSTGRES_HOST
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_HOST
          name: docker-env-db-backups-env
    - name: POSTGRES_PASS
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_PASS
          name: docker-env-db-backups-env
    - name: POSTGRES_PORT
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_PORT
          name: docker-env-db-backups-env
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          key: POSTGRES_USER
          name: docker-env-db-backups-env
    image: kartoza/pg-backup:12.0
    name: db-dbbackups
    resources: {}
    volumeMounts:
    - mountPath: /backups
      name: db-backups
  restartPolicy: OnFailure
  volumes:
  - name: db-backups
    persistentVolumeClaim:
      claimName: db-backups
status: {}
