apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: geoserver
  name: geoserver
spec:
  ports:
  - name: "8600"
    port: 8600
    targetPort: 8080
  selector:
    io.kompose.service: geoserver
status:
  loadBalancer: {}
